# Generated by Django 3.2.5 on 2021-08-14 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneBook', '0003_auto_20210715_0605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonebook',
            options={'verbose_name': 'Phone Book'},
        ),
    ]
